AWSTemplateFormatVersion: 2010-09-09
Description: This template sets up two database servers into a private subnet across two availability zones.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  KeyName:
      Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
      Type: 'AWS::EC2::KeyPair::KeyName'
      ConstraintDescription: must be the name of an existing EC2 KeyPair.
  AMItoUse:
      Description: AMI to use for our base image
      Type: String
Resources:
  DbAccessSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow mysql and ssh to our host
        VpcId:
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  DbServerInstance1: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: !Ref AMItoUse
      NetworkInterfaces: 
        - DeviceIndex: "0"
          GroupSet: 
            - Ref: "DbAccessSecurityGroup"
          SubnetId: 
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PRI1-SN"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          wget https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
          yum update -y
          yum localinstall mysql57-community-release-el7-11.noarch.rpm
          yum install -y mysql-community-server
          systemctl start mysqld.service
  DbServerInstance2: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: !Ref AMItoUse
      NetworkInterfaces: 
        - DeviceIndex: "0"
          GroupSet: 
            - Ref: "DbAccessSecurityGroup"
          SubnetId: 
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PRI2-SN"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          wget https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
          yum update -y
          yum localinstall mysql57-community-release-el7-11.noarch.rpm
          yum install -y mysql-community-server
          systemctl start mysqld.service
Outputs:
  DbServerInstance1ID:
    Description: InstanceId of the first database server
    Value: !Ref DbServerInstance1
  DbServerInstance2ID:
    Description: InstanceId of the second database server
    Value: !Ref DbServerInstance2